rm -rvf mesh_complete
rm -rvf perturbed_mesh
rm -rvf output_init
rm -rvf translation_plus_rotation_DG
rm -v meshlog_*.dat
rm -v nrm_face.dat
rm -v load_balance_*.dat
rm -v control_points.vts
rm -v counts*.txt
rm -v arg_dict_output.jl
